# Generated by Django 4.2.13 on 2024-06-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RankingGerentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efetividade', models.IntegerField(default=0)),
                ('base_de_varejos', models.IntegerField(default=0)),
                ('adimplencia_prime', models.IntegerField(default=0)),
                ('id_ulp', models.IntegerField(default=0)),
                ('vol_prime', models.IntegerField(default=0)),
                ('positivacao_parc', models.IntegerField(default=0)),
                ('faturamento_parc', models.IntegerField(default=0)),
                ('ytd_base_direta', models.IntegerField(default=0)),
                ('som_ka_cnv', models.IntegerField(default=0)),
                ('digital', models.IntegerField(default=0)),
                ('parceria', models.IntegerField(default=0)),
                ('positivacao_parc2', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RankingVendedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efetividade', models.IntegerField(default=0)),
                ('positivao_parcial', models.IntegerField(default=0)),
                ('adimplencia_prime', models.IntegerField(default=0)),
                ('id_ulp', models.IntegerField(default=0)),
                ('faturamento_parc', models.IntegerField(default=0)),
                ('digital', models.IntegerField(default=0)),
                ('base_de_varejos', models.IntegerField(default=0)),
                ('vol_prime', models.IntegerField(default=0)),
                ('boost', models.IntegerField(default=0)),
            ],
        ),
    ]
