# Generated by Django 4.2.13 on 2024-06-10 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ranking_rtm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingvendedores',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usaario_vendedor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rankinggerentes',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_gerente', to=settings.AUTH_USER_MODEL),
        ),
    ]
