# Generated by Django 4.2.13 on 2024-06-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking_rtm', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingRegionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUL', models.IntegerField(default=0)),
                ('SPR', models.IntegerField(default=0)),
                ('SPC', models.IntegerField(default=0)),
                ('RIO', models.IntegerField(default=0)),
                ('CTO', models.IntegerField(default=0)),
                ('NNE', models.IntegerField(default=0)),
                ('updatedAt', models.DateTimeField()),
            ],
        ),
    ]
