# Generated by Django 4.2.13 on 2024-06-11 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking_rtm', '0003_rankingregionais'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RankingRegionais',
        ),
    ]
