# Generated by Django 4.2.13 on 2024-06-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking_rtm', '0005_rankingregionais'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankinggerentes',
            name='date',
            field=models.DateField(default='2021-01-01'),
        ),
        migrations.AddField(
            model_name='rankingregionais',
            name='date',
            field=models.DateField(default='2021-01-01'),
        ),
        migrations.AddField(
            model_name='rankingvendedores',
            name='date',
            field=models.DateField(default='2021-01-01'),
        ),
    ]
