# Generated by Django 4.2.13 on 2024-06-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking_rtm', '0007_rankingterritorioregional'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankinggerentes',
            name='pontos_acumulados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rankingvendedores',
            name='pontos_acumulados',
            field=models.IntegerField(default=0),
        ),
    ]
