# Generated by Django 4.2.13 on 2024-06-27 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ranking_rtm', '0008_rankinggerentes_pontos_acumulados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankinggerentes',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_gerente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rankingvendedores',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_vendedor', to=settings.AUTH_USER_MODEL),
        ),
    ]
