# Generated by Django 4.2.13 on 2024-06-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking_rtm', '0009_alter_rankinggerentes_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingvendedores',
            name='ranking_br',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rankingvendedores',
            name='ranking_bu',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rankingvendedores',
            name='ranking_tv',
            field=models.IntegerField(default=0),
        ),
    ]
