# Generated by Django 4.2.13 on 2024-06-28 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking_rtm', '0010_rankingvendedores_ranking_br_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rankinggerentes',
            old_name='base_de_varejos',
            new_name='base',
        ),
        migrations.RenameField(
            model_name='rankinggerentes',
            old_name='digital',
            new_name='boost',
        ),
        migrations.RenameField(
            model_name='rankinggerentes',
            old_name='faturamento_parc',
            new_name='cobertura_vol_prime',
        ),
        migrations.RenameField(
            model_name='rankinggerentes',
            old_name='parceria',
            new_name='faturamento',
        ),
        migrations.RenameField(
            model_name='rankinggerentes',
            old_name='positivacao_parc',
            new_name='positivacao',
        ),
        migrations.RenameField(
            model_name='rankinggerentes',
            old_name='positivacao_parc2',
            new_name='pts_divers_portfolio',
        ),
        migrations.RenameField(
            model_name='rankinggerentes',
            old_name='som_ka_cnv',
            new_name='pts_share_ka_cnv',
        ),
        migrations.RenameField(
            model_name='rankinggerentes',
            old_name='vol_prime',
            new_name='pts_ytd_direto',
        ),
        migrations.RemoveField(
            model_name='rankinggerentes',
            name='ytd_base_direta',
        ),
    ]
