# Generated by Django 4.2.13 on 2024-06-28 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking_rtm', '0011_rename_base_de_varejos_rankinggerentes_base_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rankingvendedores',
            old_name='base_de_varejos',
            new_name='base',
        ),
        migrations.RenameField(
            model_name='rankingvendedores',
            old_name='boost',
            new_name='cobertura_vol_prime',
        ),
        migrations.RenameField(
            model_name='rankingvendedores',
            old_name='digital',
            new_name='faturamento',
        ),
        migrations.RenameField(
            model_name='rankingvendedores',
            old_name='faturamento_parc',
            new_name='positivacao',
        ),
        migrations.RemoveField(
            model_name='rankingvendedores',
            name='positivao_parcial',
        ),
        migrations.RemoveField(
            model_name='rankingvendedores',
            name='vol_prime',
        ),
    ]
