# Generated by Django 4.2.13 on 2024-06-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Vendedor', 'Vendedor'), ('Gerente', 'Gerente')], default='Vendedor', max_length=20),
        ),
    ]
