# Generated by Django 4.2.13 on 2024-06-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_user_deleted_at_alter_user_deleted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='regional',
            field=models.CharField(choices=[('SUL', 'SUL'), ('SPR', 'SPR'), ('SPC', 'SPC'), ('RIO', 'RIO'), ('CTO', 'CTO'), ('NNE', 'NNE')], default='SUL', max_length=5),
        ),
    ]
