# Generated by Django 4.2.13 on 2024-06-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='territorio',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
