# Generated by Django 4.2.13 on 2024-06-28 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_user_ranking_br_user_ranking_bu_user_ranking_tv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ranking_br',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ranking_bu',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ranking_tv',
        ),
    ]
